name: build

on:
  push:
    tags:
      - '*'

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      # The `fetch-depth: 0` is important to fetch all the tags
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set version
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  build:
    runs-on: macos-latest
    needs: [version]
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          brew install go-task
          task package oses='darwin linux windows' archs='amd64 arm64'

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/*.zip

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      # The `fetch-depth: 0` is important to fetch all the tags
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Fetch artifact
        uses: actions/download-artifact@v4
        with:
          path: binaries
          merge-multiple: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Create the changelog
        run: |
          pnpm install -g release-it @release-it/conventional-changelog
          release-it --ci

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.version.outputs.VERSION }}
          tag: ${{ needs.version.outputs.VERSION }}
          bodyFile: CHANGELOG.md
          replacesArtifacts: true
          artifacts: binaries/*.zip